package dev.oneapp.plugin

/**
 * Trust level assigned to each installed plugin.
 *
 * OWN      — generated by your own evolution agent. Full capabilities.
 * TRUSTED  — external plugin explicitly approved by the user. Full capabilities.
 * EXTERNAL — installed from a deep link, not yet reviewed. Restricted capabilities:
 *              - No dangerous Android permissions
 *              - No HTTP POST (prevents data exfiltration)
 *              - No custom HTTP headers (prevents credential passing)
 *              - Storage isolated to own plugin ID only
 *
 * Note: Java-level restrictions cannot prevent reflection-based escapes by a
 * truly adversarial plugin. Trust levels defend against careless/opportunistic
 * attacks and clearly communicate risk to the user. Code review remains the
 * primary defense for TRUSTED plugins.
 */
enum class PluginTrust { OWN, TRUSTED, EXTERNAL }
